### ISSUE TITLE
face landmarks  order seems not correct 

### ISSUE THREAD

**Issue by ghgggg** [namdvt/SCRFD_FaceDetection_TensorRT#2]
I modified the  func "draw"  color to get the order of face landmarks ，but i found they differ  when input changed
![image](https://user-images.githubusercontent.com/17875613/224885512-6adc4d28-b215-4e63-846e-6665541fac92.png)

and the landmarks code below

`obj.landmark[0].x = cx + kps_blob[8*q*w*h + i*w + j] * feat_stride;
obj.landmark[0].y = cy + kps_blob[(8*q + 1)*w*h + i*w + j] * feat_stride;
obj.landmark[1].x = cx + kps_blob[(8*q + 2)*w*h + i*w + j] * feat_stride;
obj.landmark[1].y = cy + kps_blob[(8*q + 3)*w*h + i*w + j] * feat_stride;
obj.landmark[2].x = cx + kps_blob[(8*q + 4)*w*h + i*w + j] * feat_stride;
obj.landmark[2].y = cy + kps_blob[(8*q + 5)*w*h + i*w + j] * feat_stride;
obj.landmark[3].x = cx + kps_blob[(8*q + 6)*w*h + i*w + j] * feat_stride;
obj.landmark[3].y = cy + kps_blob[(8*q + 7)*w*h + i*w + j] * feat_stride;
obj.landmark[4].x = cx + kps_blob[(8*q + 8)*w*h + i*w + j] * feat_stride;
obj.landmark[4].y = cy + kps_blob[(8*q + 9)*w*h + i*w + j] * feat_stride;`

in `kps_blob[(8*q + 9)*w*h + i*w + j]`
is 8 right here？or it shoud be 10？
could you give me some advice please? Thanks you

**Comment by namdvt** [comment]
As I understand, you only need to modify the draw function. If you want to get the order of face landmarks, you can simply check the landmarks' corrdinates.

**Comment by cyrusbehr** [comment]
@ghgggg is correct.
In order to achieve consistent landmark results, it needs to be 

```
                    obj.landmark[0].x = cx + kps_blob[10*q*w*h + i*w + j] * feat_stride;
                    obj.landmark[0].y = cy + kps_blob[(10*q + 1)*w*h + i*w + j] * feat_stride;
                    obj.landmark[1].x = cx + kps_blob[(10*q + 2)*w*h + i*w + j] * feat_stride;
                    obj.landmark[1].y = cy + kps_blob[(10*q + 3)*w*h + i*w + j] * feat_stride;
                    obj.landmark[2].x = cx + kps_blob[(10*q + 4)*w*h + i*w + j] * feat_stride;
                    obj.landmark[2].y = cy + kps_blob[(10*q + 5)*w*h + i*w + j] * feat_stride;
                    obj.landmark[3].x = cx + kps_blob[(10*q + 6)*w*h + i*w + j] * feat_stride;
                    obj.landmark[3].y = cy + kps_blob[(10*q + 7)*w*h + i*w + j] * feat_stride;
                    obj.landmark[4].x = cx + kps_blob[(10*q + 8)*w*h + i*w + j] * feat_stride;
                    obj.landmark[4].y = cy + kps_blob[(10*q + 9)*w*h + i*w + j] * feat_stride;

```

**Comment by ghgggg** [comment]
> I modified the func "draw" color to get the order of face landmarks ，but i found they differ when input changed ![image](https://user-images.githubusercontent.com/17875613/224885512-6adc4d28-b215-4e63-846e-6665541fac92.png)
> 
> and the landmarks code below
> 
> `obj.landmark[0].x = cx + kps_blob[8*q*w*h + i*w + j] * feat_stride; obj.landmark[0].y = cy + kps_blob[(8*q + 1)*w*h + i*w + j] * feat_stride; obj.landmark[1].x = cx + kps_blob[(8*q + 2)*w*h + i*w + j] * feat_stride; obj.landmark[1].y = cy + kps_blob[(8*q + 3)*w*h + i*w + j] * feat_stride; obj.landmark[2].x = cx + kps_blob[(8*q + 4)*w*h + i*w + j] * feat_stride; obj.landmark[2].y = cy + kps_blob[(8*q + 5)*w*h + i*w + j] * feat_stride; obj.landmark[3].x = cx + kps_blob[(8*q + 6)*w*h + i*w + j] * feat_stride; obj.landmark[3].y = cy + kps_blob[(8*q + 7)*w*h + i*w + j] * feat_stride; obj.landmark[4].x = cx + kps_blob[(8*q + 8)*w*h + i*w + j] * feat_stride; obj.landmark[4].y = cy + kps_blob[(8*q + 9)*w*h + i*w + j] * feat_stride;`
> 
> in `kps_blob[(8*q + 9)*w*h + i*w + j]` is 8 right here？or it shoud be 10？ could you give me some advice please? Thanks you

yes,10 is correct here. @cyrusbehr LOL
