### ISSUE TITLE
Input defined in scrfd_trt.h does not match model's input name

### ISSUE THREAD

**Issue by cyrusbehr** [namdvt/SCRFD_FaceDetection_TensorRT#3]
First of all, thank you for putting this together. 

In your documentation, you have the input name specified as `input.1`, which is correct. However, in your actual code, you have it labeled as `image` [here](https://github.com/namdvt/SCRFD_FaceDetection_TensorRT/blob/f265679045c11c654778bc68d79775f890b0a472/scrfd_trt.h#L74).

![image](https://user-images.githubusercontent.com/17056751/227082211-693b98aa-bdee-47ec-a10a-3134fed388d2.png)

**Comment by namdvt** [comment]
You are correct. They should be consistent with the ONNX and TRT files. Thank you for your interest.

**Comment by cyrusbehr** [comment]
Ok, I just wanted to make you aware in-case you want to fix it in your code, up to you. Closing the issue since you are aware of it.

**Comment by namdvt** [comment]
Thank you. I have updated it.
